export const REGISTER_ADMIN = 'REGISTER_ADMIN';
export const REGISTER_ADMIN_SUCCESSFUL = 'REGISTER_ADMIN_SUCCESSFUL';
export const REGISTER_ADMIN_FAILED = 'REGISTER_ADMIN_FAILED';


export const SET_REGISTER_LOADING = 'SET_REGISTER_LOADING';



