export const GET_ARTICLE_CATEGORIES = 'GET_ARTICLE_CATEGORIES';
export const GET_ARTICLE_CATEGORIES_SUCCESSFUL = 'GET_ARTICLE_CATEGORIES_SUCCESSFUL';
export const GET_ARTICLE_CATEGORIES_FAILED = 'GET_ARTICLE_CATEGORIES_FAILED';

export const GET_ARTICLES_BY_CATEGORY = 'GET_ARTICLES_BY_CATEGORY';
export const GET_ARTICLES_BY_CATEGORY_SUCCESSFUL = 'GET_ARTICLES_BY_CATEGORY_SUCCESSFUL';
export const GET_ARTICLES_BY_CATEGORY_FAILED = 'GET_ARTICLES_BY_CATEGORY_FAILED';

export const GET_POPULAR_ARTICLES = 'GET_POPULAR_ARTICLES';
export const GET_POPULAR_ARTICLES_SUCCESSFUL = 'GET_POPULAR_ARTICLES_SUCCESSFUL';
export const GET_POPULAR_ARTICLES_FAILED = 'GET_POPULAR_ARTICLES_FAILED';

export const GET_FEATURED_ARTICLES = 'GET_FEATURED_ARTICLES';
export const GET_FEATURED_ARTICLES_SUCCESSFUL = 'GET_FEATURED_ARTICLES_SUCCESSFUL';
export const GET_FEATURED_ARTICLES_FAILED = 'GET_FEATURED_ARTICLES_FAILED';

export const GET_SORTED_ARTICLES = 'GET_SORTED_ARTICLES';
export const GET_SORTED_ARTICLES_SUCCESSFUL = 'GET_SORTED_ARTICLES_SUCCESSFUL';
export const GET_SORTED_ARTICLES_FAILED = 'GET_SORTED_ARTICLES_FAILED';


export const GET_FILTERED_ARTICLES = 'GET_FILTERED_ARTICLES';
export const GET_FILTERED_ARTICLES_SUCCESSFUL = 'GET_FILTERED_ARTICLES_SUCCESSFUL';
export const GET_FILTERED_ARTICLES_FAILED = 'GET_FILTERED_ARTICLES_FAILED';

export const GET_BOOKMARKED_ARTICLES = 'GET_BOOKMARKED_ARTICLES';
export const GET_BOOKMARKED_ARTICLES_SUCCESSFUL = 'GET_BOOKMARKED_ARTICLES_SUCCESSFUL';
export const GET_BOOKMARKED_ARTICLES_FAILED = 'GET_BOOKMARKED_ARTICLES_FAILED';

export const REMOVE_BOOKMARKED_ARTICLES = 'REMOVE_BOOKMARKED_ARTICLES';
export const REMOVE_BOOKMARKED_ARTICLES_SUCCESSFUL = 'REMOVE_BOOKMARKED_ARTICLES_SUCCESSFUL';
export const REMOVE_BOOKMARKED_ARTICLES_FAILED = 'REMOVE_BOOKMARKED_ARTICLES_FAILED';

export const BOOKMARK_ARTICLE = 'BOOKMARK_ARTICLE';
export const BOOKMARK_ARTICLE_SUCCESSFUL = 'BOOKMARK_ARTICLE_SUCCESSFUL';
export const BOOKMARK_ARTICLE_FAILED = 'BOOKMARK_ARTICLE_FAILED';

export const GET_ARTICLE_BY_ID = 'GET_ARTICLE_BY_ID';
export const GET_ARTICLE_BY_ID_SUCCESSFUL = 'GET_ARTICLE_BY_ID_SUCCESSFUL';
export const GET_ARTICLE_BY_ID_FAILED = 'GET_ARTICLE_BY_ID_FAILED';

export const GET_RECOMMENDED_PRODUCTS = 'GET_RECOMMENDED_PRODUCTS';
export const GET_RECOMMENDED_PRODUCTS_SUCCESSFUL = 'GET_RECOMMENDED_PRODUCTS_SUCCESSFUL';
export const GET_RECOMMENDED_PRODUCTS_FAILED = 'GET_RECOMMENDED_PRODUCTS_FAILED';

export const GET_RECOMMENDED_SERVICES = 'GET_RECOMMENDED_SERVICES';
export const GET_RECOMMENDED_SERVICES_SUCCESSFUL = 'GET_RECOMMENDED_SERVICES_SUCCESSFUL';
export const GET_RECOMMENDED_SERVICES_FAILED = 'GET_RECOMMENDED_SERVICES_FAILED';

export const SORT_AND_FILTER_ARTICLES = 'SORT_AND_FILTER_ARTICLES';
export const SORT_AND_FILTER_ARTICLES_SUCCESSFUL = 'SORT_AND_FILTER_ARTICLES_SUCCESSFUL';
export const SORT_AND_FILTER_ARTICLES_FAILED = 'SORT_AND_FILTER_ARTICLES_FAILED';

export const SET_SORT_AND_FILTER = 'SET_SORT_AND_FILTER';

export const SET_SORT_BY = 'SET_SORT_BY';
export const SET_FILTER_BY = 'SET_FILTER_BY';
export const SET_SEARCH = 'SET_SEARCH';
export const SET_QUERY = 'SET_QUERY';
export const SET_EXPLORE_IN = 'SET_EXPLORE_IN';
export const SET_SELECTED_CATEGORY = 'SET_SELECTED_CATEGORY';

export const RESET_SORT_FILTER_QUERY_SEARCH = 'RESET_SORT_FILTER_QUERY_SEARCH';
export const RESET_EXPLORE_IN = 'RESET_EXPLORE_IN';


export const SET_ARTICLE_CATEGORY_LOADING = 'SET_ARTICLE_CATEGORY_LOADING';
export const SET_BOOKMARK_LOADER = 'SET_BOOKMARK_LOADER';
export const RESET_ARTICLE_SUCCESS_STATUS ='RESET_ARTICLE_SUCCESS_STATUS';



