export const GET_ALL_PROVINCE = 'GET_ALL_PROVINCE';
export const GET_ALL_PROVINCE_SUCCESSFUL = "GET_ALL_PROVINCE_SUCCESSFUL";
export const GET_ALL_PROVINCE_FAILED = 'GET_ALL_PROVINCE_FAILED';

export const GET_ALL_LOCATIONS = 'GET_ALL_LOCATIONS';
export const GET_ALL_LOCATIONS_SUCCESSFUL = "GET_ALL_LOCATIONS_SUCCESSFUL";
export const GET_ALL_LOCATIONS_FAILED = 'GET_ALL_LOCATIONS_FAILED';




