export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_SUCCESSFUL = 'GET_CATEGORIES_SUCCESSFUL';
export const GET_CATEGORIES_FAILED = 'GET_CATEGORIES_FAILED';

export const GET_POPULAR_STORES = 'GET_POPULAR_STORES';
export const GET_POPULAR_STORES_SUCCESSFUL = 'GET_POPULAR_STORES_SUCCESSFUL';
export const GET_POPULAR_STORES_FAILED = 'GET_POPULAR_STORES_FAILED';


export const SET_HOME_LOADING = 'SET_HOME_LOADING';
export const SET_CATEGORY_SECTION_LOADING = 'SET_CATEGORY_SECTION_LOADING';



