export const FORGET_PASSWORD = "FORGET_PASSWORD";
export const FORGET_PASSWORD_SUCCESS = "FORGET_PASSWORD_SUCCESS";
export const FORGET_PASSWORD_ERROR = "FORGET_PASSWORD_ERROR";
export const RESET_FORGET_PASSWORD_ERROR_MESSAGE = "RESET_FORGET_PASSWORD_ERROR_MESSAGE";
